name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: pnpm setup
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: install dependencies
        run: pnpm install

      - name: build project
        run: pnpm run build

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ./dist

  deploy:
    name: deploy
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: ./dist

      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
